/*
 * generated by Xtext 2.28.0
 */
package ddm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ddm.TwitterQARuntimeModule;
import ddm.TwitterQAStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TwitterQAIdeSetup extends TwitterQAStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TwitterQARuntimeModule(), new TwitterQAIdeModule()));
	}
	
}
