/*
 * generated by Xtext 2.28.0
 */
package ddm.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TwitterQAGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TwitterQAElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.TwitterQA");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTwitterQAKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConsumer_keyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConsumer_keyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConsumer_keyEStringParserRuleCall_3_0 = (RuleCall)cConsumer_keyAssignment_3.eContents().get(0);
		private final Keyword cConsumer_secretKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cConsumer_secretAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cConsumer_secretEStringParserRuleCall_5_0 = (RuleCall)cConsumer_secretAssignment_5.eContents().get(0);
		private final Keyword cAccess_tokenKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAccess_tokenAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAccess_tokenEStringParserRuleCall_7_0 = (RuleCall)cAccess_tokenAssignment_7.eContents().get(0);
		private final Keyword cAccess_token_secretKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cAccess_token_secretAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cAccess_token_secretEStringParserRuleCall_9_0 = (RuleCall)cAccess_token_secretAssignment_9.eContents().get(0);
		private final Keyword cWelcome_msgKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cWelcome_msgAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cWelcome_msgEStringParserRuleCall_11_0 = (RuleCall)cWelcome_msgAssignment_11.eContents().get(0);
		private final Keyword cGamesKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cGamesAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cGamesGameParserRuleCall_14_0 = (RuleCall)cGamesAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cGamesAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cGamesGameParserRuleCall_15_1_0 = (RuleCall)cGamesAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cLocationsKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cLeftCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cLocationsAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cLocationsLocationParserRuleCall_19_0 = (RuleCall)cLocationsAssignment_19.eContents().get(0);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cCommaKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Assignment cLocationsAssignment_20_1 = (Assignment)cGroup_20.eContents().get(1);
		private final RuleCall cLocationsLocationParserRuleCall_20_1_0 = (RuleCall)cLocationsAssignment_20_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_21 = (Keyword)cGroup.eContents().get(21);
		private final Keyword cRightCurlyBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		
		//TwitterQA returns TwitterQA:
		//    'TwitterQA'
		//    '{'
		//        'consumer_key' consumer_key=EString
		//        'consumer_secret' consumer_secret=EString
		//        'access_token' access_token=EString
		//        'access_token_secret' access_token_secret=EString
		//        'welcome_msg' welcome_msg=EString
		//        'games' '{' games+=Game ( "," games+=Game)* '}'
		//        'locations' '{' locations+=Location ( "," locations+=Location)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'TwitterQA'
		//'{'
		//    'consumer_key' consumer_key=EString
		//    'consumer_secret' consumer_secret=EString
		//    'access_token' access_token=EString
		//    'access_token_secret' access_token_secret=EString
		//    'welcome_msg' welcome_msg=EString
		//    'games' '{' games+=Game ( "," games+=Game)* '}'
		//    'locations' '{' locations+=Location ( "," locations+=Location)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'TwitterQA'
		public Keyword getTwitterQAKeyword_0() { return cTwitterQAKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'consumer_key'
		public Keyword getConsumer_keyKeyword_2() { return cConsumer_keyKeyword_2; }
		
		//consumer_key=EString
		public Assignment getConsumer_keyAssignment_3() { return cConsumer_keyAssignment_3; }
		
		//EString
		public RuleCall getConsumer_keyEStringParserRuleCall_3_0() { return cConsumer_keyEStringParserRuleCall_3_0; }
		
		//'consumer_secret'
		public Keyword getConsumer_secretKeyword_4() { return cConsumer_secretKeyword_4; }
		
		//consumer_secret=EString
		public Assignment getConsumer_secretAssignment_5() { return cConsumer_secretAssignment_5; }
		
		//EString
		public RuleCall getConsumer_secretEStringParserRuleCall_5_0() { return cConsumer_secretEStringParserRuleCall_5_0; }
		
		//'access_token'
		public Keyword getAccess_tokenKeyword_6() { return cAccess_tokenKeyword_6; }
		
		//access_token=EString
		public Assignment getAccess_tokenAssignment_7() { return cAccess_tokenAssignment_7; }
		
		//EString
		public RuleCall getAccess_tokenEStringParserRuleCall_7_0() { return cAccess_tokenEStringParserRuleCall_7_0; }
		
		//'access_token_secret'
		public Keyword getAccess_token_secretKeyword_8() { return cAccess_token_secretKeyword_8; }
		
		//access_token_secret=EString
		public Assignment getAccess_token_secretAssignment_9() { return cAccess_token_secretAssignment_9; }
		
		//EString
		public RuleCall getAccess_token_secretEStringParserRuleCall_9_0() { return cAccess_token_secretEStringParserRuleCall_9_0; }
		
		//'welcome_msg'
		public Keyword getWelcome_msgKeyword_10() { return cWelcome_msgKeyword_10; }
		
		//welcome_msg=EString
		public Assignment getWelcome_msgAssignment_11() { return cWelcome_msgAssignment_11; }
		
		//EString
		public RuleCall getWelcome_msgEStringParserRuleCall_11_0() { return cWelcome_msgEStringParserRuleCall_11_0; }
		
		//'games'
		public Keyword getGamesKeyword_12() { return cGamesKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//games+=Game
		public Assignment getGamesAssignment_14() { return cGamesAssignment_14; }
		
		//Game
		public RuleCall getGamesGameParserRuleCall_14_0() { return cGamesGameParserRuleCall_14_0; }
		
		//( "," games+=Game)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//games+=Game
		public Assignment getGamesAssignment_15_1() { return cGamesAssignment_15_1; }
		
		//Game
		public RuleCall getGamesGameParserRuleCall_15_1_0() { return cGamesGameParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//'locations'
		public Keyword getLocationsKeyword_17() { return cLocationsKeyword_17; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_18() { return cLeftCurlyBracketKeyword_18; }
		
		//locations+=Location
		public Assignment getLocationsAssignment_19() { return cLocationsAssignment_19; }
		
		//Location
		public RuleCall getLocationsLocationParserRuleCall_19_0() { return cLocationsLocationParserRuleCall_19_0; }
		
		//( "," locations+=Location)*
		public Group getGroup_20() { return cGroup_20; }
		
		//","
		public Keyword getCommaKeyword_20_0() { return cCommaKeyword_20_0; }
		
		//locations+=Location
		public Assignment getLocationsAssignment_20_1() { return cLocationsAssignment_20_1; }
		
		//Location
		public RuleCall getLocationsLocationParserRuleCall_20_1_0() { return cLocationsLocationParserRuleCall_20_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_21() { return cRightCurlyBracketKeyword_21; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_22() { return cRightCurlyBracketKeyword_22; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.Game");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDescriptionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionEStringParserRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cCityKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCityAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCityEStringParserRuleCall_6_0 = (RuleCall)cCityAssignment_6.eContents().get(0);
		private final Keyword cInitial_testKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cInitial_testAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cInitial_testTestParserRuleCall_8_0 = (RuleCall)cInitial_testAssignment_8.eContents().get(0);
		private final Keyword cTestsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cTestsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cTestsTestParserRuleCall_11_0 = (RuleCall)cTestsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cTestsAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final RuleCall cTestsTestParserRuleCall_12_1_0 = (RuleCall)cTestsAssignment_12_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Game returns Game:
		//    'Game'
		//    id=EString
		//    '{'
		//        'description' description=EString
		//        'city' city=EString
		//        'initial_test' initial_test=Test
		//        'tests' '{' tests+=Test ( "," tests+=Test)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Game'
		//id=EString
		//'{'
		//    'description' description=EString
		//    'city' city=EString
		//    'initial_test' initial_test=Test
		//    'tests' '{' tests+=Test ( "," tests+=Test)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'description'
		public Keyword getDescriptionKeyword_3() { return cDescriptionKeyword_3; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_0() { return cDescriptionEStringParserRuleCall_4_0; }
		
		//'city'
		public Keyword getCityKeyword_5() { return cCityKeyword_5; }
		
		//city=EString
		public Assignment getCityAssignment_6() { return cCityAssignment_6; }
		
		//EString
		public RuleCall getCityEStringParserRuleCall_6_0() { return cCityEStringParserRuleCall_6_0; }
		
		//'initial_test'
		public Keyword getInitial_testKeyword_7() { return cInitial_testKeyword_7; }
		
		//initial_test=Test
		public Assignment getInitial_testAssignment_8() { return cInitial_testAssignment_8; }
		
		//Test
		public RuleCall getInitial_testTestParserRuleCall_8_0() { return cInitial_testTestParserRuleCall_8_0; }
		
		//'tests'
		public Keyword getTestsKeyword_9() { return cTestsKeyword_9; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10() { return cLeftCurlyBracketKeyword_10; }
		
		//tests+=Test
		public Assignment getTestsAssignment_11() { return cTestsAssignment_11; }
		
		//Test
		public RuleCall getTestsTestParserRuleCall_11_0() { return cTestsTestParserRuleCall_11_0; }
		
		//( "," tests+=Test)*
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//tests+=Test
		public Assignment getTestsAssignment_12_1() { return cTestsAssignment_12_1; }
		
		//Test
		public RuleCall getTestsTestParserRuleCall_12_1_0() { return cTestsTestParserRuleCall_12_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.Location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLatitudeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLatitudeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLatitudeEDoubleParserRuleCall_4_0 = (RuleCall)cLatitudeAssignment_4.eContents().get(0);
		private final Keyword cLongitudeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLongitudeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLongitudeEDoubleParserRuleCall_6_0 = (RuleCall)cLongitudeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Location returns Location:
		//    'Location'
		//    name=EString
		//    '{'
		//        'latitude' latitude=EDouble
		//        'longitude' longitude=EDouble
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Location'
		//name=EString
		//'{'
		//    'latitude' latitude=EDouble
		//    'longitude' longitude=EDouble
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Location'
		public Keyword getLocationKeyword_0() { return cLocationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'latitude'
		public Keyword getLatitudeKeyword_3() { return cLatitudeKeyword_3; }
		
		//latitude=EDouble
		public Assignment getLatitudeAssignment_4() { return cLatitudeAssignment_4; }
		
		//EDouble
		public RuleCall getLatitudeEDoubleParserRuleCall_4_0() { return cLatitudeEDoubleParserRuleCall_4_0; }
		
		//'longitude'
		public Keyword getLongitudeKeyword_5() { return cLongitudeKeyword_5; }
		
		//longitude=EDouble
		public Assignment getLongitudeAssignment_6() { return cLongitudeAssignment_6; }
		
		//EDouble
		public RuleCall getLongitudeEDoubleParserRuleCall_6_0() { return cLongitudeEDoubleParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdEStringParserRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cQuestionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cQuestionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuestionEStringParserRuleCall_4_0 = (RuleCall)cQuestionAssignment_4.eContents().get(0);
		private final Keyword cAnswersKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cAnswersAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cAnswersEStringParserRuleCall_7_0 = (RuleCall)cAnswersAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAnswersAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAnswersEStringParserRuleCall_8_1_0 = (RuleCall)cAnswersAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHintsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cHintsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cHintsEStringParserRuleCall_10_2_0 = (RuleCall)cHintsAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cHintsAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cHintsEStringParserRuleCall_10_3_1_0 = (RuleCall)cHintsAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cTimelimitKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cTimelimitAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cTimelimitEIntParserRuleCall_12_0 = (RuleCall)cTimelimitAssignment_12.eContents().get(0);
		private final Keyword cAttemptsKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cAttemptsAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cAttemptsEIntParserRuleCall_14_0 = (RuleCall)cAttemptsAssignment_14.eContents().get(0);
		private final Keyword cRewardKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cRewardAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cRewardEIntParserRuleCall_16_0 = (RuleCall)cRewardAssignment_16.eContents().get(0);
		private final Keyword cLocationKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cLocationAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final CrossReference cLocationLocationCrossReference_18_0 = (CrossReference)cLocationAssignment_18.eContents().get(0);
		private final RuleCall cLocationLocationEStringParserRuleCall_18_0_1 = (RuleCall)cLocationLocationCrossReference_18_0.eContents().get(1);
		private final Group cGroup_19 = (Group)cGroup.eContents().get(19);
		private final Keyword cOn_correctKeyword_19_0 = (Keyword)cGroup_19.eContents().get(0);
		private final Assignment cOn_correctAssignment_19_1 = (Assignment)cGroup_19.eContents().get(1);
		private final CrossReference cOn_correctTestCrossReference_19_1_0 = (CrossReference)cOn_correctAssignment_19_1.eContents().get(0);
		private final RuleCall cOn_correctTestEStringParserRuleCall_19_1_0_1 = (RuleCall)cOn_correctTestCrossReference_19_1_0.eContents().get(1);
		private final Group cGroup_20 = (Group)cGroup.eContents().get(20);
		private final Keyword cOn_timeoutKeyword_20_0 = (Keyword)cGroup_20.eContents().get(0);
		private final Assignment cOn_timeoutAssignment_20_1 = (Assignment)cGroup_20.eContents().get(1);
		private final CrossReference cOn_timeoutTestCrossReference_20_1_0 = (CrossReference)cOn_timeoutAssignment_20_1.eContents().get(0);
		private final RuleCall cOn_timeoutTestEStringParserRuleCall_20_1_0_1 = (RuleCall)cOn_timeoutTestCrossReference_20_1_0.eContents().get(1);
		private final Group cGroup_21 = (Group)cGroup.eContents().get(21);
		private final Keyword cOn_failKeyword_21_0 = (Keyword)cGroup_21.eContents().get(0);
		private final Assignment cOn_failAssignment_21_1 = (Assignment)cGroup_21.eContents().get(1);
		private final CrossReference cOn_failTestCrossReference_21_1_0 = (CrossReference)cOn_failAssignment_21_1.eContents().get(0);
		private final RuleCall cOn_failTestEStringParserRuleCall_21_1_0_1 = (RuleCall)cOn_failTestCrossReference_21_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_22 = (Keyword)cGroup.eContents().get(22);
		
		//Test returns Test:
		//    'Test'
		//    id=EString
		//    '{'
		//        'question' question=EString
		//        'answers' '{' answers+=EString ( "," answers+=EString)* '}'
		//        ('hints' '{' hints+=EString ( "," hints+=EString)* '}' )?
		//        'timelimit' timelimit=EInt
		//        'attempts' attempts=EInt
		//        'reward' reward=EInt
		//        'location' location=[Location|EString]
		//        ('on_correct' on_correct=[Test|EString])?
		//        ('on_timeout' on_timeout=[Test|EString])?
		//        ('on_fail' on_fail=[Test|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Test'
		//id=EString
		//'{'
		//    'question' question=EString
		//    'answers' '{' answers+=EString ( "," answers+=EString)* '}'
		//    ('hints' '{' hints+=EString ( "," hints+=EString)* '}' )?
		//    'timelimit' timelimit=EInt
		//    'attempts' attempts=EInt
		//    'reward' reward=EInt
		//    'location' location=[Location|EString]
		//    ('on_correct' on_correct=[Test|EString])?
		//    ('on_timeout' on_timeout=[Test|EString])?
		//    ('on_fail' on_fail=[Test|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Test'
		public Keyword getTestKeyword_0() { return cTestKeyword_0; }
		
		//id=EString
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }
		
		//EString
		public RuleCall getIdEStringParserRuleCall_1_0() { return cIdEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'question'
		public Keyword getQuestionKeyword_3() { return cQuestionKeyword_3; }
		
		//question=EString
		public Assignment getQuestionAssignment_4() { return cQuestionAssignment_4; }
		
		//EString
		public RuleCall getQuestionEStringParserRuleCall_4_0() { return cQuestionEStringParserRuleCall_4_0; }
		
		//'answers'
		public Keyword getAnswersKeyword_5() { return cAnswersKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//answers+=EString
		public Assignment getAnswersAssignment_7() { return cAnswersAssignment_7; }
		
		//EString
		public RuleCall getAnswersEStringParserRuleCall_7_0() { return cAnswersEStringParserRuleCall_7_0; }
		
		//( "," answers+=EString)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//answers+=EString
		public Assignment getAnswersAssignment_8_1() { return cAnswersAssignment_8_1; }
		
		//EString
		public RuleCall getAnswersEStringParserRuleCall_8_1_0() { return cAnswersEStringParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//('hints' '{' hints+=EString ( "," hints+=EString)* '}' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'hints'
		public Keyword getHintsKeyword_10_0() { return cHintsKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//hints+=EString
		public Assignment getHintsAssignment_10_2() { return cHintsAssignment_10_2; }
		
		//EString
		public RuleCall getHintsEStringParserRuleCall_10_2_0() { return cHintsEStringParserRuleCall_10_2_0; }
		
		//( "," hints+=EString)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//hints+=EString
		public Assignment getHintsAssignment_10_3_1() { return cHintsAssignment_10_3_1; }
		
		//EString
		public RuleCall getHintsEStringParserRuleCall_10_3_1_0() { return cHintsEStringParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'timelimit'
		public Keyword getTimelimitKeyword_11() { return cTimelimitKeyword_11; }
		
		//timelimit=EInt
		public Assignment getTimelimitAssignment_12() { return cTimelimitAssignment_12; }
		
		//EInt
		public RuleCall getTimelimitEIntParserRuleCall_12_0() { return cTimelimitEIntParserRuleCall_12_0; }
		
		//'attempts'
		public Keyword getAttemptsKeyword_13() { return cAttemptsKeyword_13; }
		
		//attempts=EInt
		public Assignment getAttemptsAssignment_14() { return cAttemptsAssignment_14; }
		
		//EInt
		public RuleCall getAttemptsEIntParserRuleCall_14_0() { return cAttemptsEIntParserRuleCall_14_0; }
		
		//'reward'
		public Keyword getRewardKeyword_15() { return cRewardKeyword_15; }
		
		//reward=EInt
		public Assignment getRewardAssignment_16() { return cRewardAssignment_16; }
		
		//EInt
		public RuleCall getRewardEIntParserRuleCall_16_0() { return cRewardEIntParserRuleCall_16_0; }
		
		//'location'
		public Keyword getLocationKeyword_17() { return cLocationKeyword_17; }
		
		//location=[Location|EString]
		public Assignment getLocationAssignment_18() { return cLocationAssignment_18; }
		
		//[Location|EString]
		public CrossReference getLocationLocationCrossReference_18_0() { return cLocationLocationCrossReference_18_0; }
		
		//EString
		public RuleCall getLocationLocationEStringParserRuleCall_18_0_1() { return cLocationLocationEStringParserRuleCall_18_0_1; }
		
		//('on_correct' on_correct=[Test|EString])?
		public Group getGroup_19() { return cGroup_19; }
		
		//'on_correct'
		public Keyword getOn_correctKeyword_19_0() { return cOn_correctKeyword_19_0; }
		
		//on_correct=[Test|EString]
		public Assignment getOn_correctAssignment_19_1() { return cOn_correctAssignment_19_1; }
		
		//[Test|EString]
		public CrossReference getOn_correctTestCrossReference_19_1_0() { return cOn_correctTestCrossReference_19_1_0; }
		
		//EString
		public RuleCall getOn_correctTestEStringParserRuleCall_19_1_0_1() { return cOn_correctTestEStringParserRuleCall_19_1_0_1; }
		
		//('on_timeout' on_timeout=[Test|EString])?
		public Group getGroup_20() { return cGroup_20; }
		
		//'on_timeout'
		public Keyword getOn_timeoutKeyword_20_0() { return cOn_timeoutKeyword_20_0; }
		
		//on_timeout=[Test|EString]
		public Assignment getOn_timeoutAssignment_20_1() { return cOn_timeoutAssignment_20_1; }
		
		//[Test|EString]
		public CrossReference getOn_timeoutTestCrossReference_20_1_0() { return cOn_timeoutTestCrossReference_20_1_0; }
		
		//EString
		public RuleCall getOn_timeoutTestEStringParserRuleCall_20_1_0_1() { return cOn_timeoutTestEStringParserRuleCall_20_1_0_1; }
		
		//('on_fail' on_fail=[Test|EString])?
		public Group getGroup_21() { return cGroup_21; }
		
		//'on_fail'
		public Keyword getOn_failKeyword_21_0() { return cOn_failKeyword_21_0; }
		
		//on_fail=[Test|EString]
		public Assignment getOn_failAssignment_21_1() { return cOn_failAssignment_21_1; }
		
		//[Test|EString]
		public CrossReference getOn_failTestCrossReference_21_1_0() { return cOn_failTestCrossReference_21_1_0; }
		
		//EString
		public RuleCall getOn_failTestEStringParserRuleCall_21_1_0_1() { return cOn_failTestEStringParserRuleCall_21_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_22() { return cRightCurlyBracketKeyword_22; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ddm.TwitterQA.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	
	private final TwitterQAElements pTwitterQA;
	private final EStringElements pEString;
	private final GameElements pGame;
	private final LocationElements pLocation;
	private final TestElements pTest;
	private final EIntElements pEInt;
	private final EDoubleElements pEDouble;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TwitterQAGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTwitterQA = new TwitterQAElements();
		this.pEString = new EStringElements();
		this.pGame = new GameElements();
		this.pLocation = new LocationElements();
		this.pTest = new TestElements();
		this.pEInt = new EIntElements();
		this.pEDouble = new EDoubleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ddm.TwitterQA".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TwitterQA returns TwitterQA:
	//    'TwitterQA'
	//    '{'
	//        'consumer_key' consumer_key=EString
	//        'consumer_secret' consumer_secret=EString
	//        'access_token' access_token=EString
	//        'access_token_secret' access_token_secret=EString
	//        'welcome_msg' welcome_msg=EString
	//        'games' '{' games+=Game ( "," games+=Game)* '}'
	//        'locations' '{' locations+=Location ( "," locations+=Location)* '}'
	//    '}';
	public TwitterQAElements getTwitterQAAccess() {
		return pTwitterQA;
	}
	
	public ParserRule getTwitterQARule() {
		return getTwitterQAAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Game returns Game:
	//    'Game'
	//    id=EString
	//    '{'
	//        'description' description=EString
	//        'city' city=EString
	//        'initial_test' initial_test=Test
	//        'tests' '{' tests+=Test ( "," tests+=Test)* '}'
	//    '}';
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//Location returns Location:
	//    'Location'
	//    name=EString
	//    '{'
	//        'latitude' latitude=EDouble
	//        'longitude' longitude=EDouble
	//    '}';
	public LocationElements getLocationAccess() {
		return pLocation;
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}
	
	//Test returns Test:
	//    'Test'
	//    id=EString
	//    '{'
	//        'question' question=EString
	//        'answers' '{' answers+=EString ( "," answers+=EString)* '}'
	//        ('hints' '{' hints+=EString ( "," hints+=EString)* '}' )?
	//        'timelimit' timelimit=EInt
	//        'attempts' attempts=EInt
	//        'reward' reward=EInt
	//        'location' location=[Location|EString]
	//        ('on_correct' on_correct=[Test|EString])?
	//        ('on_timeout' on_timeout=[Test|EString])?
	//        ('on_fail' on_fail=[Test|EString])?
	//    '}';
	public TestElements getTestAccess() {
		return pTest;
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
