/*
 * generated by Xtext 2.28.0
 */
package ddm.ui;

import com.google.inject.Injector;
import ddm.TwitterQA.ui.internal.TwitterQAActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TwitterQAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TwitterQAActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TwitterQAActivator activator = TwitterQAActivator.getInstance();
		return activator != null ? activator.getInjector(TwitterQAActivator.DDM_TWITTERQA) : null;
	}

}
