/*
 * generated by Xtext 2.28.0
 */
package ddm.ui.tests;

import com.google.inject.Injector;
import ddm.twitterQA.ui.internal.TwitterQAActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TwitterQAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TwitterQAActivator.getInstance().getInjector("ddm.TwitterQA");
	}

}
