/*
 * generated by Xtext 2.28.0
 */
package ddm.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import ddm.ide.contentassist.antlr.internal.InternalTwitterQAParser;
import ddm.services.TwitterQAGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TwitterQAParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TwitterQAGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TwitterQAGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getTwitterQAAccess().getGroup(), "rule__TwitterQA__Group__0");
			builder.put(grammarAccess.getTwitterQAAccess().getGroup_21(), "rule__TwitterQA__Group_21__0");
			builder.put(grammarAccess.getTwitterQAAccess().getGroup_27(), "rule__TwitterQA__Group_27__0");
			builder.put(grammarAccess.getGameAccess().getGroup(), "rule__Game__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup_16(), "rule__Game__Group_16__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getTestAccess().getGroup(), "rule__Test__Group__0");
			builder.put(grammarAccess.getTestAccess().getGroup_13(), "rule__Test__Group_13__0");
			builder.put(grammarAccess.getTestAccess().getGroup_15(), "rule__Test__Group_15__0");
			builder.put(grammarAccess.getTestAccess().getGroup_15_4(), "rule__Test__Group_15_4__0");
			builder.put(grammarAccess.getTestAccess().getGroup_28(), "rule__Test__Group_28__0");
			builder.put(grammarAccess.getTestAccess().getGroup_29(), "rule__Test__Group_29__0");
			builder.put(grammarAccess.getTestAccess().getGroup_30(), "rule__Test__Group_30__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getTwitterQAAccess().getConsumer_keyAssignment_4(), "rule__TwitterQA__Consumer_keyAssignment_4");
			builder.put(grammarAccess.getTwitterQAAccess().getConsumer_secretAssignment_7(), "rule__TwitterQA__Consumer_secretAssignment_7");
			builder.put(grammarAccess.getTwitterQAAccess().getAccess_tokenAssignment_10(), "rule__TwitterQA__Access_tokenAssignment_10");
			builder.put(grammarAccess.getTwitterQAAccess().getAccess_token_secretAssignment_13(), "rule__TwitterQA__Access_token_secretAssignment_13");
			builder.put(grammarAccess.getTwitterQAAccess().getWelcome_msgAssignment_16(), "rule__TwitterQA__Welcome_msgAssignment_16");
			builder.put(grammarAccess.getTwitterQAAccess().getGamesAssignment_20(), "rule__TwitterQA__GamesAssignment_20");
			builder.put(grammarAccess.getTwitterQAAccess().getGamesAssignment_21_1(), "rule__TwitterQA__GamesAssignment_21_1");
			builder.put(grammarAccess.getTwitterQAAccess().getLocationsAssignment_26(), "rule__TwitterQA__LocationsAssignment_26");
			builder.put(grammarAccess.getTwitterQAAccess().getLocationsAssignment_27_1(), "rule__TwitterQA__LocationsAssignment_27_1");
			builder.put(grammarAccess.getGameAccess().getNameAssignment_1(), "rule__Game__NameAssignment_1");
			builder.put(grammarAccess.getGameAccess().getDescriptionAssignment_5(), "rule__Game__DescriptionAssignment_5");
			builder.put(grammarAccess.getGameAccess().getCityAssignment_8(), "rule__Game__CityAssignment_8");
			builder.put(grammarAccess.getGameAccess().getInitial_testAssignment_11(), "rule__Game__Initial_testAssignment_11");
			builder.put(grammarAccess.getGameAccess().getTestsAssignment_15(), "rule__Game__TestsAssignment_15");
			builder.put(grammarAccess.getGameAccess().getTestsAssignment_16_1(), "rule__Game__TestsAssignment_16_1");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_1(), "rule__Location__NameAssignment_1");
			builder.put(grammarAccess.getLocationAccess().getLatitudeAssignment_5(), "rule__Location__LatitudeAssignment_5");
			builder.put(grammarAccess.getLocationAccess().getLongitudeAssignment_8(), "rule__Location__LongitudeAssignment_8");
			builder.put(grammarAccess.getTestAccess().getNameAssignment_1(), "rule__Test__NameAssignment_1");
			builder.put(grammarAccess.getTestAccess().getQuestionAssignment_5(), "rule__Test__QuestionAssignment_5");
			builder.put(grammarAccess.getTestAccess().getOrderAssignment_8(), "rule__Test__OrderAssignment_8");
			builder.put(grammarAccess.getTestAccess().getAnswersAssignment_12(), "rule__Test__AnswersAssignment_12");
			builder.put(grammarAccess.getTestAccess().getAnswersAssignment_13_1(), "rule__Test__AnswersAssignment_13_1");
			builder.put(grammarAccess.getTestAccess().getHintsAssignment_15_3(), "rule__Test__HintsAssignment_15_3");
			builder.put(grammarAccess.getTestAccess().getHintsAssignment_15_4_1(), "rule__Test__HintsAssignment_15_4_1");
			builder.put(grammarAccess.getTestAccess().getTimelimitAssignment_18(), "rule__Test__TimelimitAssignment_18");
			builder.put(grammarAccess.getTestAccess().getAttemptsAssignment_21(), "rule__Test__AttemptsAssignment_21");
			builder.put(grammarAccess.getTestAccess().getRewardAssignment_24(), "rule__Test__RewardAssignment_24");
			builder.put(grammarAccess.getTestAccess().getLocationAssignment_27(), "rule__Test__LocationAssignment_27");
			builder.put(grammarAccess.getTestAccess().getOn_correctAssignment_28_2(), "rule__Test__On_correctAssignment_28_2");
			builder.put(grammarAccess.getTestAccess().getOn_timeoutAssignment_29_2(), "rule__Test__On_timeoutAssignment_29_2");
			builder.put(grammarAccess.getTestAccess().getOn_failAssignment_30_2(), "rule__Test__On_failAssignment_30_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TwitterQAGrammarAccess grammarAccess;

	@Override
	protected InternalTwitterQAParser createParser() {
		InternalTwitterQAParser result = new InternalTwitterQAParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TwitterQAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TwitterQAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
