/*
 * generated by Xtext 2.28.0
 */
package ddm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TwitterQAUiModule extends AbstractTwitterQAUiModule {

	public TwitterQAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
