/*
 * generated by Xtext 2.28.0
 */
package ddm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTwitterQAScopeProvider extends DelegatingScopeProvider {
}
