/*
 * generated by Xtext 2.28.0
 */
package ddm.parser.antlr;

import com.google.inject.Inject;
import ddm.parser.antlr.internal.InternalTwitterQAParser;
import ddm.services.TwitterQAGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TwitterQAParser extends AbstractAntlrParser {

	@Inject
	private TwitterQAGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTwitterQAParser createParser(XtextTokenStream stream) {
		return new InternalTwitterQAParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TwitterQA";
	}

	public TwitterQAGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TwitterQAGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
