/*
 * generated by Xtext 2.28.0
 */
package ddm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TwitterQAStandaloneSetup extends TwitterQAStandaloneSetupGenerated {

	public static void doSetup() {
		new TwitterQAStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
